### ISSUE TITLE
Copying static assets to build directory.

### ISSUE THREAD

**Issue by tomc974** [dojo/cli-build-app#102]
Hi,

 I would like to know if there is a feature to copy static assets (images, JSON files...) to the output directory when building an application. If not, are you considering adding this feature or do you recommend to do it by other means?

**Comment by agubler** [comment]
Hi @tomc974, including static assets is on the roadmap for the version 4.0.0 release.

We are planning to implement:
* Automatic copying, hashing and linking to resources linked in a projects index.html
* A catch all fallback of copying assets from a users `public` directory in the project (these will not be hashed)

Separate issues will be raised to track these two changes

**Comment by agubler** [comment]
Both #124 and #125 have been merged and will be available in the next major release.
