### ISSUE TITLE
Support .dojorc parameters override using CLI

### ISSUE THREAD

**Issue by evra** [dojo/cli-build-app#103]
It would be a usefull feature to support `.dojorc` configuration parameters override using CLI options. At least having a possibility to override `features` parameter of the `cli-build-app` config. 

Our usecase: override `has` features in the `.dojorc` using CLI in order to produce different builds for different environments (CI builds). 

Similar approch works quite well in the https://github.com/theintern/intern

**Comment by devpaul** [comment]
I took a look at this. A possible approach to doing this would to simply support an `override` cli argument that would be mixed in with the `.dojorc` config.

Usage would look something like this:

```
> npx dojo build --mode dist --no-override.features.foo --override.features.bar --override.features.baz=baz
```

The above override would totally replace the `features` object with a new object:

```
{
  features: {
    foo: false,
    bar: true,
    baz: 'baz'
  }
}
```

I'm trying to decide whether it would be better to always replace a top-level configuration (e.g. `features`) when using cli overrides or mixin the leaf values. IIRC Intern always replaces unless a `+` is used and then it appends.

WIP: https://github.com/devpaul/cli-build-app/commit/662f06eb8f20722c766135fc89a382eda24d623e

**Comment by agubler** [comment]
@devpaul I raised a change to support features like we discussed yesterday, hopefully we can get this reviewed and back-ported to v3 to enable consumers to have different builds that target different envs.
