### ISSUE TITLE
Zero Configuration Code Splitting for Routes

### ISSUE THREAD

**Issue by agubler** [dojo/cli-build-app#122]
**Enhancement**

Currently cli-build-app supports code splitting using configuration specified in a project's `.dojorc` file. This means that consumers have to always be aware as features get added to the application and adjust the configuration appropriately. 

The goal is to have a mechanism that provides automatic code splitting based on application routes  within the application, this should remove the current overhead on consumers.

**Comment by matt-gadd** [comment]
fixed in https://github.com/dojo/cli-build-app/pull/168
