### ISSUE TITLE
Including assets from a projects index.html

### ISSUE THREAD

**Issue by agubler** [dojo/cli-build-app#124]
It would be ideal if we could automatically copy, hash and linking to resources that a user has linked in their project's `index.html`

**Comment by mwistrand** [comment]
Are there any limitations on what assets are included? For example, do we want to include _everything_ (basically any `<link href="">` or anything with an `src` attribute), or do we want to limit it so, say, `<link>` elements in the `<head>`?

**Comment by matt-gadd** [comment]
@mwistrand no limitations (ie we'd want to include js resources which would likely be in script tags in the body)

**Comment by agubler** [comment]
Resolved by #131
