### ISSUE TITLE
Import statements sometimes missing from source maps @dojo/cli-build-app@3.0.5

### ISSUE THREAD

**Issue by MarvDann** [dojo/cli-build-app#142]
With the lastest @dojo/cli-build-app@3.0.5 I witnessed some source maps that exclude import statements causing incorrect line numbers to be reported when debugging the original source in vscode.

This doesn't cause a problem when debugging in chrome dev tools and breakpoints can still be hit there.

![source-map-issue](https://user-images.githubusercontent.com/14371546/44455369-c7a74980-a5f5-11e8-9037-6fa3f9a65dfd.png)

**Comment by rorticus** [comment]
@MarvDann says this has been working in 3.0.6 so this may have been fixed. Feel free to reopen this issue if it comes up again.
