### ISSUE TITLE
nested css not working with cli-build-app-3.0.5

### ISSUE THREAD

**Issue by krezovic** [dojo/cli-build-app#143]
Works fine in 3.0.4, I suspect postcss upgrade broke it.

This does not work anymore

```
.class1 {
  & .class2 {
    h1 {
      width: 100%
    }
  }
}
```

it is not transpiled to proper css anymore. Target css has the same format as written above.

**Comment by agubler** [comment]
Upgrading to `postcss-preset-env`, does not include nesting by default (because it is a stage: 1 feature) which needs to be explicitly turned out to fix this.
