### ISSUE TITLE
Erroneously prints out the project version rather than the command version

### ISSUE THREAD

**Issue by matt-gadd** [dojo/cli-build-app#163]
The command output erroneously shows the version of the project it is in, rather than the version of the actual command.

**Comment by mwistrand** [comment]
This is true of all commands (see dojo/cli#196).

**Comment by matt-gadd** [comment]
@mwistrand that is a different issue when actually using the `dojo version` command. this is directly related to cli-build-app's output

**Comment by matt-gadd** [comment]
here is the error: https://github.com/dojo/cli-build-app/blob/master/src/logger.ts#L13

**Comment by mwistrand** [comment]
Ah, thanks for clarifying.

**Comment by matt-gadd** [comment]
fixed in https://github.com/dojo/cli-build-app/pull/182, thanks to @jamesvhays
