### ISSUE TITLE
Static assets not always updating in watch mode

### ISSUE THREAD

**Issue by KaneFreeman** [dojo/cli-build-app#194]
**Bug**

Static assets in the `assets` folder do not always cause a rebuild in `--watch` mode.

Package Version: 4.0.0

**Expected behavior:**

Any changes in the contents of the `assets` folder should trigger a rebuild.

**Actual behavior:**

The rebuild will only happen once per file (1 update), after which any additional changes are ignored. You have to stop and restart the build process to get the changes.

**Comment by agubler** [comment]
Resolved by https://github.com/dojo/cli-build-app/pull/227
