### ISSUE TITLE
Sometimes out of sync CSS modules

### ISSUE THREAD

**Issue by kitsonk** [dojo/cli-build-app#20]
**Bug**

This occurred with `cli-build-webpack` but it has started occurring for me with `cli-build-app` as well.  Sometimes when adding new classes to a CSS Module, the type definitions are not generated in time for the TypeScript compile to complete and I will get red herrings on `dojo build` and have to repeat the build to clear the error.  For example when adding some classes and immediately used them in a widget I got the following:

```
errors:
./src/widgets/StoreTravel.ts
[tsl] ERROR in /Users/kitsonk/github/devtool/src/widgets/StoreTravel.ts(34,50)
      TS2339: Property 'timeline' does not exist on type 'typeof "/Users/kitsonk/github/devtool/src/widgets/styles/storetravel.m.css"'.,./src/widge
ts/StoreTravel.ts
[tsl] ERROR in /Users/kitsonk/github/devtool/src/widgets/StoreTravel.ts(35,51)
      TS2339: Property 'slider' does not exist on type 'typeof "/Users/kitsonk/github/devtool/src/widgets/styles/storetravel.m.css"'.
```

When performing a subsequent `dojo build` without any further changes, the errors were no longer present.

**Comment by matt-gadd** [comment]
this is very difficult to fix with the existing ts-loader interactions with webpack. An easier solution/workaround would be to add an ambient type for `m.css` which I think would at least mean the build does not fail.
