### ISSUE TITLE
ecstatic version removed from npm 

### ISSUE THREAD

**Issue by matt-gadd** [dojo/cli-build-app#270]
Looks like old versions of ecstatic have been removed from the npm registry (perhaps due to: https://snyk.io/vuln/SNYK-JS-ECSTATIC-174543)
```
$ npm view ecstatic versions
[ '4.1.2' ]
```
```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for ecstatic@^3.0.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'http-server'
npm ERR! notarget
```

This affects `http-server`. There is no solution yet other than switching http-server out as ecstatic has breaking changes in 4.x
https://github.com/indexzero/http-server/pull/520

**Comment by thornjad** [comment]
See jfhbrook/node-ecstatic#255 and indexzero/http-server#520
