### ISSUE TITLE
Add static option to build time render config

### ISSUE THREAD

**Issue by matt-gadd** [dojo/cli-build-app#280]
**Enhancement** 

Now we have build time render and blocks, it's possible to build an entire static site that doesn't depend on either JS or CSS (the critical CSS is inlined into the html). 

In the future it would be cool if we could detect whether individual pages can be purely static during build time rendering (via whatever heuristics). 

For now having a single .dojorc option of `static` or similar (and/or per path?) in the build-time-render options to disable JS and CSS for all pages would be a good start.

**Comment by agubler** [comment]
Resolved by https://github.com/dojo/webpack-contrib/pull/162
