### ISSUE TITLE
Print production warning when using serve

### ISSUE THREAD

**Issue by agubler** [dojo/cli-build-app#296]
**Enhancement**

The `serve` option is not intended to be used to serve applications in production. We should add a warning message when running `serve` for the user.

**Comment by devpaul** [comment]
Right now [serve fails when not run in a one of the test modes](https://github.com/dojo/cli-build-app/blob/master/src/main.ts#L350).

Are you thinking of something like this for a warning?

https://github.com/devpaul/cli-build-app/commit/6443e0aca1133584db8c608241b6567ed7ff5629

It'll warn if `NODE_ENV === 'production'` or if they (somehow) run serve when not in a test mode,

**Comment by matt-gadd** [comment]
@devpaul no, the `serve` option should just consistently warn saying that it's not a production server (regardless of mode). preferably here: https://github.com/dojo/cli-build-app/blob/master/src/main.ts#L81, which uses the logger.
