### ISSUE TITLE
Caching issue in browsers

### ISSUE THREAD

**Issue by aldyn** [dojo/cli-build-app#304]
**Bug**

Build doesn't change hashcode of `bootstrap.xxxx.bundle.js` file

Package Version: 5.0.0 and 6.0.0

Steps to reproduce:
1. Create a new app using cli-create-app
2. Execute `npm run build`
3. Check `bootstrap.xxxx.bundle.js` file hashcode
4. Do any changes in the source
5. Repeat from 2nd step

NOTE: for `main.xxxx.bundle.js` it works nicely. After build new hashcode is provided but since there is no direct link between `index.html` file and `main.xxxx.bundle.js` file it causes caching issue in browsers, after every new release.

**Expected behavior:**

Expect to get new hashcode after every build(when changes are made).

**Actual behavior:**

Same hashcode after every build.

**Comment by krezovic** [comment]
Since 5.x is also affected by this, is it possible to backport this and create a new release for 5.x as well? TIA
