### ISSUE TITLE
Unable to load images from code split CSS 

### ISSUE THREAD

**Issue by agubler** [dojo/cli-build-app#315]
**Bug**

Assets included in CSS such as images are created at the root of the output directory, unfortunately this causes issues for assets needed by code split modules as they are written as their nested path but the assets are requested relatively to the asset. This means that it cannot be found.

**Comment by agubler** [comment]
Re-opening as the fix had to be reverted due to unintentional side affects.

**Comment by maier49** [comment]
This should be fixed by #423
