### ISSUE TITLE
Usage of --single-bundle ends with an Error in Internet Explorer

### ISSUE THREAD

**Issue by nka089** [dojo/cli-build-app#320]
**Bug** 

Usage of options --single-bundle (with--legacy) leads to an error in Internet Explorer (11)

 * Create application with `@dojo/cli-create-app`.

 * Upgrade to version 6 with `@dojo/cli-upgrade-app`.

 * run app with `--legacy` and `--single-bundle`.

Error in IE: `SCRIPT445: Object doesn't support this action`.

In contrast: running without `--single-bundle` (and only `--legacy`)  still work.

Package Version: 6.0.1

**Code**

example here:
https://github.com/nka089/single-bundle

**Expected behavior:**

Application should run, as with Dojo 5

**Actual behavior:**

**Comment by matt-gadd** [comment]
hi @nka089 thanks for raising the issue, unfortunately https://github.com/nka089/single-bundle doesn't seem to exist?

**Comment by nka089** [comment]
@matt-gadd I' sorry, forgot to make it public, please try again

**Comment by agubler** [comment]
Fixed in `cli-build-app@6.0.3`
