### ISSUE TITLE
Support ESM modules

### ISSUE THREAD

**Issue by rorticus** [dojo/cli-build-app#33]
* Right now the UglifyJS plugin does not support ES6 syntax, so we'll have to find an alternative.
* Add `.mjs` to the resolve extensions list in webpack config.

See [the changes to cli-build-webpack](https://github.com/dojo/cli-build-webpack/compare/master...rorticus:mjs) for an example!

**Comment by agubler** [comment]
This has been done with the `legacy` flag in https://github.com/dojo/cli-build-app/pull/100
