### ISSUE TITLE
Using `--serve` in test mode does not serve the test runner

### ISSUE THREAD

**Issue by agubler** [dojo/cli-build-app#40]
## Enhancement

At the moment using the `--serve` option when building in test mode is pretty useless as it serves the `output/test` directory meaning that it does not enable running the tests in the browser.

We should consider serving from the project root or disabling `--serve` when building the tests.

**Comment by mwistrand** [comment]
This is very similar to #38, which also throws in improved handling for the other modes.

**Comment by agubler** [comment]
@mwistrand excellent, I was transferring the issue from a comment on cli-build-webpack https://github.com/dojo/cli-build-webpack/issues/259#issuecomment-357373862.

If it is a duplicate of #38 feel free to close.
