### ISSUE TITLE
Avoid iltorb native dependency

### ISSUE THREAD

**Issue by willstott101** [dojo/cli-build-app#415]
Currently we depend on `brotli-webpack-plugin@1.0.0` but since `brotli-webpack-plugin@1.1.0` it's been possible to use the pure-js `brotli` package as opposed to the compiled `iltorb` extension. Having to compile native packages for a build tool seems unfortunate to me as it's often causing complications or slowing down CI builds.

Would we consider switching to using `brotli` over `iltorb`?

**Comment by willstott101** [comment]
Also FYI since v1.1.0 of that plugin it'll use node's built-in zlib library regardless of wether iltorb or brotli.js are installed... brotli compression has been native to node since v10.16

We should definitely take advantage of that.

**Comment by willstott101** [comment]
Going even further if we don't want to support pre-10.16 then https://www.npmjs.com/package/compression-webpack-plugin supports brotli itself

**Comment by matt-gadd** [comment]
Hi @willstott101 I believe we now depend on node v12 as of dojo 7, so it should be fine to drop support for both `iltorb` and simply use the option to `compression-webpack-plugin`. Do you fancy raising a Pull Request for this? 😄

**Comment by willstott101** [comment]
Yeah sure, sounds good to me. Will try and get to it today, thanks.

**Comment by agubler** [comment]
Resolved by #416 & #419
