### ISSUE TITLE
Proxy configuration not being honored

### ISSUE THREAD

**Issue by rorticus** [dojo/cli-build-app#432]
**Bug** 

Proxy configuration in `.dojorc` is not forwarding traffic as it's supposed to.

Package Version: 5.0.0

https://gitlab.com/Jackbennett/dojo-proxy-dev

**Expected behavior:**

Traffic to `/api` would be forwarded to `http://localhost/9998/`

**Actual behavior:**

Traffic to `/api` is serving the application's `index.html`

**Comment by Jackbennett** [comment]
Awesome thanks for copying the discord issue.

**Comment by icefee** [comment]
same problem.

**Comment by agubler** [comment]
@icefee This should be resolved in the 7.0.4 release of `@dojo/cli-build-app`

**Comment by agubler** [comment]
Fixed by https://github.com/dojo/cli-build-app/pull/436
