### ISSUE TITLE
Enable css-variables in our builds

### ISSUE THREAD

**Issue by tomdye** [dojo/cli-build-app#62]
As per https://caniuse.com/#feat=css-variables css-variables are now supported in most modern browsers but we compute there values and remove the actual variables from our css.

We should look to leave these in for compatible browsers via static build flags.

Worth noting that when preserving css-variables, the built output is bullet-proofed for older browsers. ie.

if you have `--red: #ff0000;` and use it on a class selector, the built output is `.className: { color: #ff0000; color: var(--red); }` so that the browser that does not understand the `var` function can fall back to the hex value.

**Comment by tomdye** [comment]
This is blocked by: https://github.com/dojo/cli-build-app/issues/63

**Comment by agubler** [comment]
This is done now in 4.0.0, uses css var and falls back to the computed version
