### ISSUE TITLE
Ship evergreen builds by default

### ISSUE THREAD

**Issue by matt-gadd** [dojo/cli-build-app#64]
At the moment we have to specifically target an evergreen browser to get a build that elides a lot of stuff that is now in all browsers - apart from IE11. We should flip this so we ship an evergreen bundle by default, and offer a legacy flag to build for IE11.

**Comment by agubler** [comment]
This is basically done, but at the moment the `legacy` flag is `true` by default (as setting to `false` by default is a breaking change) - will leave open to remind us that we need to flip that for dojo 3.0.0

**Comment by JamesMilnerUK** [comment]
@agubler not entirely sure about the internals but just be careful shipping minified ES6 code as there's a known bug on Safari. UglifyJS can get around it but you have to pass in a options flag: https://github.com/mishoo/UglifyJS2/issues/1753

**Comment by agubler** [comment]
This has been done
