### ISSUE TITLE
Upgrade to Webpack 4

### ISSUE THREAD

**Issue by matt-gadd** [dojo/cli-build-app#68]
As the title says, upgrade to webpack 4. May need changes in webpack-contrib.

**Comment by sebilasse** [comment]
I have a machine where I have to use node 10.1 – it is not `--watch`ing anymore.
Probably updating to 4 (.8.1) will solve this.

**Comment by agubler** [comment]
Thanks @sebilasse, we had an [issue](https://github.com/dojo/cli-build-app/issues/93) specifically for issues with node 10 - hopefully the changes fix the issues you're seeing with watching also. We'll be sure to test that.
