### ISSUE TITLE
Add the external-loader-plugin

### ISSUE THREAD

**Issue by matt-gadd** [dojo/cli-build-app#7]
Add the external-loader-plugin from https://github.com/dojo/webpack-contrib. Some potential complications - we no longer use the copy-webpack-plugin, as the files copied are not versioned. So if we are to use it for the external-loader-plugin, we need to decide what the versioning strategy is.

**Comment by maier49** [comment]
The more I've looked at this the more I'm thinking that versioning shouldn't really be handled by the plugin itself, for a few reasons. 

* We intentionally made as few assumptions as possible about where files are coming from (can be from `src`, `node_modules`, or wherever), which makes any kind of automatic detection of a version from a `package.json` somewhat problematic. 

* We're not making any assumptions about how modules will eventually be loaded. That makes any kind of automated remapping if we're changing the file or directory names fairly complicated as well. 

* Copying a dependency to a versioned directory is easy enough with the existing functionality, and could be documented
```
  externals: {
    dependencies: [
      "foo": {
        "from": "node_modules/foo",
        "to": "foo-1.X.X"
      }
    ]
  }
```

* These files may be the result of some other build process that might be handling versioning, and/or may be using a loader that provides cache busting. They are "external" to the build so it seems reasonable to assume that any concerns around versioning could be handled externally as well.

**Comment by matt-gadd** [comment]
As long as we make that clear to the end user that seems reasonable to me 👍
