### ISSUE TITLE
Add information about feature optimizations

### ISSUE THREAD

**Issue by dylans** [dojo/cli-build-app#75]
The content from https://github.com/dojo/cli-build-webpack/blob/master/README.md#feature-optimization (various flags offered) would probably be useful in this repo's readme.

**Comment by matt-gadd** [comment]
@dylans the feature flags now live in webpack-contrib, so likely better documented there.

**Comment by dylans** [comment]
> @dylans the feature flags now live in webpack-contrib, so likely better documented there.

I had thought about that, but my concern is that no one will ever discover them. If we decide to document them in webpack-contrib, then we should at least mention them in this readme and link to the documentation in webpack-contrib.

**Comment by agubler** [comment]
@dylans is that not already the case? https://github.com/dojo/cli-build-app#features-object

**Comment by matt-gadd** [comment]
Yeah I actually don’t want to actively list the flags here, for the end user the abstraction will be to use a target and not individual flags.
