### ISSUE TITLE
dojo build command throws error on Node 10

### ISSUE THREAD

**Issue by nicknisi** [dojo/cli-build-app#93]
When running `dojo build`, Node throws the following error with both build commands (app and widget).

```
node[54537]: ../src/node_file.cc:829:void node::fs::Stat(const FunctionCallbackInfo<v8::Value> &): Assertion `(argc) == (3)' failed.
 1: node::Abort() [/usr/local/bin/node]
 2: node::Assert(char const* const (*) [4]) [/usr/local/bin/node]
 3: node::fs::LStat(v8::FunctionCallbackInfo<v8::Value> const&) [/usr/local/bin/node]
 4: v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo*) [/usr/local/bin/node]
 5: v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) [/usr/local/bin/node]
 6: v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/usr/local/bin/node]
 7: 0xe60c938427d
```

**Comment by nicknisi** [comment]
cli-build-app issue is tracked at dojo/cli-build-app#22.

**Comment by nicknisi** [comment]
It looks like this might be with the postcss-cssnext dependency. Running the following script in Node 10 produces the same error:

```js
require('postcss-cssnext')({
	features: { autoprefixer: { browsers: ['last 2 versions', 'ie >= 10'] } }
});
```

**Comment by sebilasse** [comment]
Thanks @agubler for pointing me here :
Solved the `watch` issue / Node 10 by adding
`config.watchOptions = { aggregateTimeout: 300, poll: 2000 };`
to the `dev.config.js`

**Comment by nicknisi** [comment]
@sebilasse Thanks for the info! The `--watch` flag seems to be working for me in Node 10. Could you provide more information about what command you're running when you see issues?

**Comment by sebilasse** [comment]
@nicknisi Hm - it seems the error is not "reproducible". 
I am running `dojo build -m dev -w memory -s` – and I tried a fresh install which _was_ watching then.
 
Now _sometimes_ it is not reloading as described here
https://github.com/webpack/webpack-dev-server/issues/1405

Basically it's fine for me (seems to be more a webpack-issue and reloading is easy ;)

**Comment by rorticus** [comment]
Tested in node 10.9.0, everything seems to be 👌
